//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum Status: String, Codable {
    case alive = "alive"
    case dead = "dead"
    case unknown = "unknown"
}
