//
// StatusAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class StatusAPI {
    /**
     get status
     
     - parameter status: (query) status of character 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(status: Status, completion: @escaping ((_ data: PersonList?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder(status: status).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     get status
     - GET /
     - parameter status: (query) status of character 
     - returns: RequestBuilder<PersonList> 
     */
    open class func callGetWithRequestBuilder(status: Status) -> RequestBuilder<PersonList> {
        let path = "/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "status": status.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<PersonList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
